### ISSUE TITLE
[13.0.0-rc6] `guildLoaded` event handler is called instead of `guildCreate` after `ready`.

### ISSUE THREAD

**Issue by norio-nomura** [discordeno/discordeno#1820]
**Describe the bug** A clear and concise description of what the bug is.
In 13.0.0-rc6, `guildLoaded` event handler is called instead of `guildCreate` after `ready`.

**To Reproduce** Steps to reproduce the behavior:

```console
$ echo 'import { createBot, startBot } from "https://deno.land/x/discordeno@13.0.0-rc6/mod.ts";
  const bot = createBot({
    token: Deno.env.get("DISCORD_TOKEN")!,
    intents: ["Guilds", "GuildMessages"],
    botId: 0n,
    events: {
      ready() {
        console.log("ready");
      },
      guildCreate(bot, guild) {
        console.log("guildCreate")
      },
      guildLoaded(bot, guild) {
        console.log("guildLoaded")
      },
    },
    cache: { isAsync: false },
  });
  await startBot(bot);
  '|deno run -A -
ready
guildLoaded
^C⏎
```

**Expected behavior** A clear and concise description of what you expected to happen.
`guildCreate` event handler should be called.

**Version details (please complete the following information):**

- Discordeno version: 13.0.0-rc6
- Deno version: 1.16.3

**Additional context** Add any other context about the problem here.
`GUILD_CREATE` event is changed to `GUILD_LOADED_DD` at [here](https://github.com/discordeno/discordeno/blob/5302a78f6912419db2a3140fccba3967a4ae4670/src/ws/handleOnMessage.ts#L132).

**Comment by itohatweb** [comment]
So your bot already is in servers on start. After start shards get a ready event which contains all ids of the guilds where the bot is in. After the ready discord dispatches many guild creates for you to cache those guilds. These events we call guildLoaded.

**Comment by norio-nomura** [comment]
I don't see any good reason why discordeno should introduce it's own events into the layer that handles events from Discord.

**Comment by itohatweb** [comment]
Its because of scalability and handling initial caching.

**Comment by norio-nomura** [comment]
I don't see how discordeno will actually make use of the `GUILD_LOADED_DD` event, so I don't know if that's a good enough reason.

**Comment by Skillz4Killz** [comment]
So this problem originates because discord re-uses the GUILD_CREATE event for many many different ways without explaining what each one is in the event. `guildLoaded` is my solution for this.

Discord could easily throw a `type` property on GUILD_CREATE but for whatever reason have chosen not to do this at this time. They are emitted in various different circumstances.

1. A guild was added
2. Shard resumed
3. Unavailable guild became available
4. Initial loading when connecting to discord
5. Insert anything i didnt think of here etc...

TO SOLVE THIS I MADE THE WORKAROUND:

`guildLoaded:` Discord was aware that this guild had your bot in it before coming online and this is the first `GUILD_CREATE` event for this guild, it sent since the bot came online. This should not trigger any guildCreate functionality.

`guildCreate` Your bot was added to a new guild.

---

You can use guildLoaded for whatever you need but it should be ignored for most bots.
You can use guildCreate for things like creating a settings entry for this guild, sending a welcome/usage message to a channel or the server admins etc. Anything you want done when a guild invites your bot goes here and with discordeno you can be 100% certain this is going to be when a bot is added ONLY not the other 3-4 types of GUILD_CREATE that discord sends.

**Comment by norio-nomura** [comment]
Thanks for the explanation.
🤔 
These scenarios seem to be possible only in the presence of persistent caches. I thought caching was an option starting with 13.0.0.

**Comment by Skillz4Killz** [comment]
These happen no matter what cache system you use. The difference is just that cache layer helps you identify which is which. Because we no longer require cache layer we have to implement this workaround solution. Hopefully discord can improve this.

**Comment by norio-nomura** [comment]
> These happen no matter what cache system you use.

I see, I understand.
Aside from the pros and cons of changing the event occurrence condition, I think it would be better if it was documented that it is being changed.

By the way, 13.0.0 is great, with many welcome changes.
The behavior in 12.0.1 where messageUpdate and messageDelete would not be called if the message was not in the cache has also been fixed so that we don't have to use forked code.

Thanks again! 🙏🏻
