### ISSUE TITLE
Use deno fmt

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#1985]
Currently we do use prettier but I think the /x ranking is affected also on what formatter is used.
Also I want to go away from the auto format workflow and requiring the PR authors to use deno fmt instead of any other formatter using a test. 

Motivation behind this is that almost every PR includes unnecessary formatting changes which just make it difficult to review.

**Comment by lts20050703** [comment]
I prefer dprint over deno fmt over prettier but I know @Skillz4Killz will prefer deno fmt over dprint

**Comment by itohatweb** [comment]
The reason for deno fmt is that everyone has it without tge need to install something.

**Comment by lts20050703** [comment]
`deno fmt` then. Now let's decide styling
Four things that I need to talk
- Tabs/Spaces: I prefer tabs. My argument is
  - The purpose of Tabs is indentation. Tab is designed to be used as an indentation character
  - Tabs saves bytes
  - Using tabs avoid having to argue between 8, 4, 2, and 1 space(s) because some dev sneeds more spaces to be able to tell apart different indentation while other devs feel it's wasted screen real estate. With tabs devs can just change editor setting to display tabs size/width to their liking.
- Semicolons: I prefer no semicolons. My argument is
  - https://blog.izs.me/2010/12/an-open-letter-to-javascript-leaders-regarding/
  - No semicolon saves space
  - <img width="533" alt="image" src="https://user-images.githubusercontent.com/87189679/152348491-532dea5c-bb0e-4584-aab9-ce624a2e26e4.png">
- Single Quotes / Double Quotes / Backtick: I have no Preference, but using backtick avoids the single quote/double quote argument
- Print width (80/120): I prefer 120 because I have plenty screen width real estate

### I am aware that `deno fmt` does not allow changing things like using backtick instead of single/double quote and no semicolons, it's the reason why I want to use dprint but oh well at this point I just want to say my opinion on styling

**Comment by itohatweb** [comment]
I would prefer to not have any changes to the default. I want to avoid the introduction to configuration files, since this will lead to users ask for more and more configuration and changes which I don't want. The only real downside of this decision would be the print width which would be 80 then sadly.
