### ISSUE TITLE
Gateway: old socket not closed before starting new socket, causing sending heat beat on unready socket 

### ISSUE THREAD

**Issue by AwesomeStickz** [discordeno/discordeno#2685]
Stack tree:

```
/home/container/node_modules/ws/lib/websocket.js:441
      throw new Error('WebSocket is not open: readyState 0 (CONNECTING)');
      ^

Error: WebSocket is not open: readyState 0 (CONNECTING)
    at WebSocket.send (/home/container/node_modules/ws/lib/websocket.js:441:13)
    at Timeout._onTimeout (file:///home/container/node_modules/discordeno/esm/gateway/shard/startHeartbeating.js:19:23)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
```

Don't know any reproducible steps, it happens randomly after some hours of uptime from what I could see. It's from heartbeating as you can see in the stack tree, but my **guess** is it happens cuz Discord randomly kills WS and it could be coming cuz it tries to send a heartbeat?

**Comment by H01001000** [comment]
Since the socket.close() function we use in the gateway will not immediately close the socket, the socket still connects and pass a message for a while.

MRE: shard gets a hello event after socket.close()

fixes: 
- assign null to socket.onerror, socket.onclose, socket.onmessage when calling socket.close()
- wait until the old socket closes then start a new socket
- consider calling socket.terminate() before assigning a new socket

**Comment by Skillz4Killz** [comment]
Fixed in v19
