### ISSUE TITLE
Failed requests never resolve (Big Bot Template)

### ISSUE THREAD

**Issue by Larsundso** [discordeno/discordeno#2709]
**Describe the bug** A clear and concise description of what the bug is.
Failed requests never resolve (Big Bot Template)

**To Reproduce** Write a small mod.ts example to replicate the behavior.
Clone https://github.com/Larsundso/DDeno-BigBot-Template
Replace Token 
Replace Worker Path to match your file tree

**Expected behavior** A clear and concise description of what you expected to happen.
Resolve with Errors

**Screenshots** If applicable, add screenshots to help explain your problem.

**Version details (please complete the following information):**

- Discordeno version: 17.1.0
- Deno version: -
- Node version: v17.8.0

**Additional context** Add any other context about the problem here.
Reproduced by @AwesomeStickz and @vxern 
Likely caused in rest/runMethod.js below note `Legacy Handling to not break old code or when body is missing`

**Comment by AwesomeStickz** [comment]
More info:

Firstly **this is only an issue with bigbot template, not discordeno** internal code.

Replacing token in `config.json` won't give enough info, because in this [line](https://github.com/discordeno/discordeno/blob/main/template/bigbot/src/bot/index.ts#L20), there's:

```js
if (!BUGS_ERRORS_REPORT_WEBHOOK) return;
```

it's catching all unhandled rejections and will ignore them if no bugs error report webhook is provided.

The error happens because the error body sent from rest is somehow an empty object `{}`, which is caught [here](https://github.com/discordeno/discordeno/blob/main/rest/runMethod.ts#L64) which checks for `body` property in the received error object, which doesn't exist on the empty error object, so it's throwing an error instead of calling `rest.convertRestError`.

I'm not sure where it goes wrong about sending the error object but I didn't have enough time to find and fix this so just pointing out the details, and the fix would be to somewhere deal with sending the error object properly so that the bot process receives the full expected object and then runs `rest.convertRestError`.

**Comment by Skillz4Killz** [comment]
@Larsundso can u check if this still happens in v19?

**Comment by H01001000** [comment]
close cause big bot template does not exist anymore
