### ISSUE TITLE
feat(rest): better handling for sendRequest reject

### ISSUE THREAD

**Issue by H01001000** [discordeno/discordeno#2965]
Since the node default error throw is not able to display an object instead shows Error: [object Object] 

At
https://github.com/discordeno/discordeno/blob/main/packages/rest/src/manager.ts#L317

**Comment by H01001000** [comment]
Stale

**Comment by Fleny113** [comment]
Do we want to consider this issue?

At the moment we reject with an object without any stack trace causing a lot of guessing if you need to understand from where an api call is done with an invalid payload or whatever the issue is, the problem is that i don't think the `new Promise(...)` can keep track of the stack trace
