### ISSUE TITLE
[Bot] Customize Typings Based on DesiredProperties

### ISSUE THREAD

**Issue by Skillz4Killz** [discordeno/discordeno#2983]
**Is your feature request related to a problem? Please describe.** 
It would be better to have typings be generated automatically based on the desired properties the user provides.

**Describe the solution you'd like** 
- Possibly a CLI like `npx prisma generate` where we do `npx discordeno generate`
- Typescript generic that user provides on `createTransformers<>()` which can provide custom ones

**Describe alternatives you've considered**

**Additional context** 

With current solution it is not typesafe as a desiredPropety could be set to false and yet the typings say it exists. We could make all properties optional but that isn't exactly a good UX either.

**Comment by MatthewSH** [comment]
Would love to hop in on this conversation since it's been a topic of conversation with us on Discord, mainly around `desiredProperties`. I know our conversation has more geared towards a DD CLI. 

I'm not opposed to a CLI, I think a CLI makes sense. It allows those who use TypeScript that type safety. I can say from experience that this threw me for a loop as well, mainly cause I didn't know `desiredProperties` existed. I was calling properties that TS expected but failed when running. 

Having proper documentation, typing, and/or CLI could've mitigated that surprise and frustration for me.

**Comment by MatthewSH** [comment]
Bump for stale bot

**Comment by Fleny113** [comment]
> * Lack of typing, since it's JS only but could still leverage JSDoc using `import('my-types').Transformers` for example? Quick thought there.

We can use a similar approach to what Vite and other similar tools uses, so a function to give the type (`defineConfig`)

> * Would still need to allow importing of JS files in your TSConfig which may not be desired
> * Different languages in one codebase

I do generally prefer when the config is a typescript file, however this creates the issue of importing the file, in #3453 we already use the typescript compiler, so we could use TSC itself and manage to import the file, however I'm not sure about the user will import the file to provide it to createBot
