### ISSUE TITLE
[Feat]: Move rest proxy docker image to it's own repo

### ISSUE THREAD

**Issue by MatthewSH** [discordeno/discordeno#3200]
### Tell us what problem the feature would solve

Right now it exists inside proxies/rest, this is then built and published under [rest-proxy](https://github.com/discordeno/discordeno/pkgs/container/rest-proxy). This image is very out of date and not maintained. It also doesn't really fit into the reasoning for the repo which is for the library itself.

I'd be happy to be the codeowner for this project in another repo and I can build it from scratch using Fastify (lighter than express) and work with Fleny or whoever to support some of the new upcoming features. This would also eliminate a majority of the current security advisories we have and give me the opportunity to upgrade everything.

### Describe the solution you'd like

Create a new repo in the Discordeno org, remove the code from this repo, rebuild the passthrough in the other repo and publish rest-proxy 2.0 utilizing v19.

### Describe alternatives you've considered

N/A

**Comment by Fleny113** [comment]
If you a quick summary of all the changes needed to the rest proxy to make it play nicely with the OAuth2 and (potentially) the multi token bots:
- [Proxy] Make the webserver accept `application/x-www-form-urlencoded` (there is a Fastify package for it, `@fastify/formbody`)
- [Bot + Proxy] Change the authentication header used to something like [Proxy-Authenticate
](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Proxy-Authenticate) or else the rest manager won't be able to tell the proxy what authentication to use
- [Proxy] For #3185, I did add `updateTokenQueues` that requires direct access to the ratelimit information (`queue` and `ratelimitPaths`) so that requires an endpoint

I did marked in [ ] if the thing requires also an intervent on the bot side other than the proxy itself

**Comment by Fleny113** [comment]
Because it's not the `Authorization` header. There is no other reason for it, we could use anything[^1] we want, i said that as it is it purpose doing stuff like this i imagine since this is a proxy at the end of the day but as long as it isn't the `Authorization`, everything[^1] is fine as otherwise there is no way to tell (without more changes to the rest manager) to tell the proxy how to authenticate against discord.

[^1]: i don't think i need to say this but i will anyway: obviusly with anything/everything i refer to headers that do not have a significant value for other part of the HTTP request like Content-Type

**Comment by H01001000** [comment]
one q, is rest v19 stable?

**Comment by MatthewSH** [comment]
> one q, is rest v19 stable?

I want to say yes, I think the biggest issue with rest right now is outdated types due to API docs issue. 

We can always publish it as a `beta` or `RC` version until v19 full release and then mark it `2.0` release with the release of v19.

**Comment by MatthewSH** [comment]
> Then I might fix #2977 now

We *could* always look at leveraging `release-please`. I'm a huge backer for it! It's honestly been fantastic. It could automate so much of this, including automated changelogs, the actual release in GitHub, and tags.

**Comment by MatthewSH** [comment]
There's another issue, #2970, in regards to this proxy as well. It mentions Docker account, does this mean Dockerhub? If I recall they sunset their free organizations and we'd have to apply to be an open source organization if we wanted it there.
