### ISSUE TITLE
Adding CacheData.emojis

### ISSUE THREAD

**Issue by Scientific-Guy** [discordeno/discordeno#658]
So it will be good that if you make all emojis from all guilds cache for `cache` variable! Which will collect all emojis from all guilds. It will be good if you make a getter which will return the cache of all global emojis. This is easy to make but will be good if its built in!

https://github.com/discordeno/discordeno/blob/main/src/api/controllers/cache.ts

**Comment by itohatweb** [comment]
>cache for cache variable

what do you mean with this

**Comment by Scientific-Guy** [comment]
> > cache for cache variable
> 
> what do you mean with this

Sorry it was mistake

**Comment by Scientific-Guy** [comment]
> So my questions:
> For what would you need it? Why do you want it to be build in?
> Also I'm not sure if this solution is so good it means every time you want to get an global emoji you would iterate over every cached guild. Also what if you delete the guild from cache?
> 
> Are my questions stupid? idk

Your questions are valid lemme explain what do i actually mean:

- You can cache emojis by events too
- This idea is already implemented in discord.js itself

There is one more method to cache emojis globally using a getter (This method might be stupid):
```js
const guilds = cache.guilds;
const emojis = new Collection();

for(let i = 0; i < guilds.emojis.length; i++){
     emojis.set(guilds.emojis[i].id, guilds.emojis[i]
}

return emojis
```

This method look like pointless, but just one sort of idea!

**Comment by itohatweb** [comment]
If this is your idea I'm not so a fan of this.
Emojis are saved in `guild.emojis` adding an function to the lib which does this is not needed imo and is one of the things you can add yourself.

**Comment by Scientific-Guy** [comment]
Yeah thats why i opened this issue. Is it really worthful or not?

**Comment by RoeHH** [comment]
I don't think a function this size could not really harm the performance of a Bot.

But you can't use this feature if your bot has no Nitro, so it would be performance loss for the most dd users┗|｀O′|┛

So in conclusion: If you could make it, so the function is only used when your bot got Nitro it would be a clear Win without that check it wouldn't be that useful.

**Comment by itohatweb** [comment]
Bots can use global emojis without nitro

**Comment by RoeHH** [comment]
Ok then it is a clear win I would say

**Comment by itohatweb** [comment]
But dd aims to be a minimalistic lib idk if this is a really necessary function.

**Comment by RoeHH** [comment]
You could implement it so it is calable and ppl that need it could call it in onRedy()

**Comment by itohatweb** [comment]
imo this is one of the things you should implement yourself. When we start adding small functions like this we will get more and more issues asking for similar things.

But could also be that I'm not understanding the use case of this function.

**Comment by ayntee** [comment]
+1 for `cache.emojis` support

**Comment by ayntee** [comment]
I take it back lol

**Comment by Scientific-Guy** [comment]
Then yeah i accept that the lib should be small and easy. But for that you should actually make a guides site where you can explain people how to make these small functions.

**Comment by Skillz4Killz** [comment]
I think this is a fair request tbh, i've myself needed this at times but i also see everyones points as well. In my opinion, perhaps there are some things everyone is not taking into consideration.

Current:

- `guild.emojis` is very performant!

Proposed: 

- `guild.emojis` is still fast but lot slower compared to before. Why because everytime you write guild.emojis, whats actually happening behind the scenes is a massive loops on every single emoji in existance. First it has to iterate and make an array then it has to iterate and filter out emojis not in this guild then create a new collection for the remaining ones.


**MY IDEA:**

We add a `cache.emojis` that is a getter that combines all the emojis from all guilds. Emojis therefore remain in `guild` which keeps guild.emojis optimal! It also allows a cache.emojis when it is desired(i've needed thismyself as well so i understand the desire), and it is the best performance wise because you are unlikely to do cache.emojis except when you want all emojis.

**Comment by Scientific-Guy** [comment]
Thats what i am actually requesting for.
