### ISSUE TITLE
Add a validate name function

### ISSUE THREAD

**Issue by itohatweb** [discordeno/discordeno#702]
We have a few functions like `editMember` and `createWebhook` which all accept a name param. Since Discord has specific [rules](https://discord.com/developers/docs/resources/user#usernames-and-nicknames) on how usernames/nicknames should be formatted we should add a check for it.

**Comment by pawanakhil** [comment]
Would like to work on this. Thanks.

**Comment by itohatweb** [comment]
please not now

**Comment by Skillz4Killz** [comment]
@pawanakhil Feel free to send a PR that adds the function itself, just dont edit the files to use it yet. Wait for itoh to be ready on that end. Doing it this way will make it so there are no merge conflicts with typings since all your doing is adding something new and not removing anything or editing anything
